[book]
authors = ["KriukovIuN"]
language = "en"
multilingual = false
src = "src"
title = "Team portfolio"
# [preprocessor.pagetoc]
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0"
# [output.html]
# additional-css = ["theme/pagetoc.css","theme/mdbook-admonish.css"]
# additional-js  = ["theme/pagetoc.js"]
