[book]
authors = ["KriukovIuN"]
language = "en"
multilingual = false
src = "src"
title = "Team portfolio"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
[preprocessor.admonish]
command = "mdbook-admonish"
[output.html]
additional-css = ["./mdbook-admonish.css"]
